// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: protobuf/review/review.proto

package review

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookId        string                 `protobuf:"bytes,2,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"` // 1-5 stars
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_protobuf_review_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_review_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_protobuf_review_review_proto_rawDescGZIP(), []int{0}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *Review) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type AddReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReviewRequest) Reset() {
	*x = AddReviewRequest{}
	mi := &file_protobuf_review_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReviewRequest) ProtoMessage() {}

func (x *AddReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_review_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReviewRequest.ProtoReflect.Descriptor instead.
func (*AddReviewRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_review_review_proto_rawDescGZIP(), []int{1}
}

func (x *AddReviewRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *AddReviewRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *AddReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *AddReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type AddReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      string                 `protobuf:"bytes,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReviewResponse) Reset() {
	*x = AddReviewResponse{}
	mi := &file_protobuf_review_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReviewResponse) ProtoMessage() {}

func (x *AddReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_review_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReviewResponse.ProtoReflect.Descriptor instead.
func (*AddReviewResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_review_review_proto_rawDescGZIP(), []int{2}
}

func (x *AddReviewResponse) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

type GetReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsRequest) Reset() {
	*x = GetReviewsRequest{}
	mi := &file_protobuf_review_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsRequest) ProtoMessage() {}

func (x *GetReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_review_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_review_review_proto_rawDescGZIP(), []int{3}
}

func (x *GetReviewsRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type GetReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	AverageRating float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsResponse) Reset() {
	*x = GetReviewsResponse{}
	mi := &file_protobuf_review_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsResponse) ProtoMessage() {}

func (x *GetReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_review_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetReviewsResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_review_review_proto_rawDescGZIP(), []int{4}
}

func (x *GetReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *GetReviewsResponse) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

type GetBookWithReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookWithReviewsRequest) Reset() {
	*x = GetBookWithReviewsRequest{}
	mi := &file_protobuf_review_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookWithReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookWithReviewsRequest) ProtoMessage() {}

func (x *GetBookWithReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_review_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookWithReviewsRequest.ProtoReflect.Descriptor instead.
func (*GetBookWithReviewsRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_review_review_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookWithReviewsRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

type BookInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookInfo) Reset() {
	*x = BookInfo{}
	mi := &file_protobuf_review_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookInfo) ProtoMessage() {}

func (x *BookInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_review_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookInfo.ProtoReflect.Descriptor instead.
func (*BookInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_review_review_proto_rawDescGZIP(), []int{6}
}

func (x *BookInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetBookWithReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *BookInfo              `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Reviews       []*Review              `protobuf:"bytes,2,rep,name=reviews,proto3" json:"reviews,omitempty"`
	AverageRating float64                `protobuf:"fixed64,3,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookWithReviewsResponse) Reset() {
	*x = GetBookWithReviewsResponse{}
	mi := &file_protobuf_review_review_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookWithReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookWithReviewsResponse) ProtoMessage() {}

func (x *GetBookWithReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_review_review_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookWithReviewsResponse.ProtoReflect.Descriptor instead.
func (*GetBookWithReviewsResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_review_review_proto_rawDescGZIP(), []int{7}
}

func (x *GetBookWithReviewsResponse) GetBook() *BookInfo {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *GetBookWithReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *GetBookWithReviewsResponse) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

var File_protobuf_review_review_proto protoreflect.FileDescriptor

const file_protobuf_review_review_proto_rawDesc = "" +
	"\n" +
	"\x1cprotobuf/review/review.proto\x12\x06review\"\x9f\x01\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\abook_id\x18\x02 \x01(\tR\x06bookId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"z\n" +
	"\x10AddReviewRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"0\n" +
	"\x11AddReviewResponse\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\tR\breviewId\",\n" +
	"\x11GetReviewsRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"e\n" +
	"\x12GetReviewsResponse\x12(\n" +
	"\areviews\x18\x01 \x03(\v2\x0e.review.ReviewR\areviews\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\"4\n" +
	"\x19GetBookWithReviewsRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\"^\n" +
	"\bBookInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"\x93\x01\n" +
	"\x1aGetBookWithReviewsResponse\x12$\n" +
	"\x04book\x18\x01 \x01(\v2\x10.review.BookInfoR\x04book\x12(\n" +
	"\areviews\x18\x02 \x03(\v2\x0e.review.ReviewR\areviews\x12%\n" +
	"\x0eaverage_rating\x18\x03 \x01(\x01R\raverageRating2\xf3\x01\n" +
	"\rReviewService\x12@\n" +
	"\tAddReview\x12\x18.review.AddReviewRequest\x1a\x19.review.AddReviewResponse\x12C\n" +
	"\n" +
	"GetReviews\x12\x19.review.GetReviewsRequest\x1a\x1a.review.GetReviewsResponse\x12[\n" +
	"\x12GetBookWithReviews\x12!.review.GetBookWithReviewsRequest\x1a\".review.GetBookWithReviewsResponseB\x1bZ\x19grpc-test/protobuf/reviewb\x06proto3"

var (
	file_protobuf_review_review_proto_rawDescOnce sync.Once
	file_protobuf_review_review_proto_rawDescData []byte
)

func file_protobuf_review_review_proto_rawDescGZIP() []byte {
	file_protobuf_review_review_proto_rawDescOnce.Do(func() {
		file_protobuf_review_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_review_review_proto_rawDesc), len(file_protobuf_review_review_proto_rawDesc)))
	})
	return file_protobuf_review_review_proto_rawDescData
}

var file_protobuf_review_review_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protobuf_review_review_proto_goTypes = []any{
	(*Review)(nil),                     // 0: review.Review
	(*AddReviewRequest)(nil),           // 1: review.AddReviewRequest
	(*AddReviewResponse)(nil),          // 2: review.AddReviewResponse
	(*GetReviewsRequest)(nil),          // 3: review.GetReviewsRequest
	(*GetReviewsResponse)(nil),         // 4: review.GetReviewsResponse
	(*GetBookWithReviewsRequest)(nil),  // 5: review.GetBookWithReviewsRequest
	(*BookInfo)(nil),                   // 6: review.BookInfo
	(*GetBookWithReviewsResponse)(nil), // 7: review.GetBookWithReviewsResponse
}
var file_protobuf_review_review_proto_depIdxs = []int32{
	0, // 0: review.GetReviewsResponse.reviews:type_name -> review.Review
	6, // 1: review.GetBookWithReviewsResponse.book:type_name -> review.BookInfo
	0, // 2: review.GetBookWithReviewsResponse.reviews:type_name -> review.Review
	1, // 3: review.ReviewService.AddReview:input_type -> review.AddReviewRequest
	3, // 4: review.ReviewService.GetReviews:input_type -> review.GetReviewsRequest
	5, // 5: review.ReviewService.GetBookWithReviews:input_type -> review.GetBookWithReviewsRequest
	2, // 6: review.ReviewService.AddReview:output_type -> review.AddReviewResponse
	4, // 7: review.ReviewService.GetReviews:output_type -> review.GetReviewsResponse
	7, // 8: review.ReviewService.GetBookWithReviews:output_type -> review.GetBookWithReviewsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_review_review_proto_init() }
func file_protobuf_review_review_proto_init() {
	if File_protobuf_review_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_review_review_proto_rawDesc), len(file_protobuf_review_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_review_review_proto_goTypes,
		DependencyIndexes: file_protobuf_review_review_proto_depIdxs,
		MessageInfos:      file_protobuf_review_review_proto_msgTypes,
	}.Build()
	File_protobuf_review_review_proto = out.File
	file_protobuf_review_review_proto_goTypes = nil
	file_protobuf_review_review_proto_depIdxs = nil
}
